package mod.upcraftlp.colorfulsheep;

import core.upcraftlp.craftdev.api.util.UpdateChecker;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import static mod.upcraftlp.colorfulsheep.Reference.*;

@Mod(
        certificateFingerprint = FINGERPRINT_KEY,
        name = MODNAME,
        version = VERSION,
        acceptedMinecraftVersions = MCVERSIONS,
        modid = MODID,
        dependencies = DEPENDENCIES,
        updateJSON = UPDATE_JSON,
        acceptableRemoteVersions = "*"
)
public class Main {

    @Mod.Instance(MODID)
    public static Main INSTANCE;

    private static final Logger log = LogManager.getLogger(MODID);

    public static Logger getLogger() {
        return log;
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        if(event.getSide() == Side.CLIENT) {
            ModMetadata data = event.getModMetadata();
            data.autogenerated = false;
            data.authorList = authors;
            data.credits = CREDITS;
            data.description = MOD_DESCRIPTION;
            data.url = WEBSITE;
        }
        if(Loader.isModLoaded("craftdevcore")) UpdateChecker.registerMod(Reference.MODID);
        log.info("Mod loaded.");
    }

}
